update lint script

diff --git a/script/lint b/script/lint
--- a/script/lint
+++ b/script/lint
@@ -4,5 +4,17 @@ set -euo pipefail
 
 source script/env "$@"
 
-go fmt -mod=vendor ./...
-golangci-lint run --fix
+STATUS=0
+assert-nothing-changed() {
+    local diff
+    "$@" >/dev/null || return 1
+    if ! diff="$(git diff -U1 --color --exit-code)"; then
+    printf '\e[31mError: running `\e[1m%s\e[22m` results in modifications that you must check into version control:\e[0m\n%s\n\n' "$*" "$diff" >&2
+    STATUS=1
+    fi
+}
+
+assert-nothing-changed go fmt -mod=vendor ./...
+assert-nothing-changed go mod tidy
+
+exit $STATUS
